packaging/samba-4.18.spec.j2
packaging/samba-master.spec.j2

* Adapt master spec file to align more with [Fedora variant](https://src.fedoraproject.org/rpms/samba/blob/main/f/samba.spec).
* Create new spec file for v4.18 as a copy of current master spec file.
Depends on https://github.com/samba-in-kubernetes/samba-centosci/pull/5

Enhance and add v4.18 spec file

---

packaging/samba-master.spec.j2

Nearly 25 changes from [2534aba94d2dc854fcf695924262fc3512b54b7a](https://git.samba.org/?p=samba.git;a=commit;h=2534aba94d2dc854fcf695924262fc3512b54b7a) introduced new python module subdirectories _domain_ and _claim_. Also add the resultant SO file.

Add new python module subdirectories and library files

---

packaging/samba-master.spec.j2

Following error is seen with latest changes in upstream during domain provision:
```
2023-03-23 20:47:34,311 pid:7 /usr/lib64/python3.10/site-packages/samba/provision/__init__.py #2021: Fixing provision GUIDs ERROR(<class 'ModuleNotFoundError'>): uncaught exception - No module named 'markdown'
File "/usr/lib64/python3.10/site-packages/samba/netcmd/__init__.py", line 230, in _run
return self.run(*args, **kwargs)
File "/usr/lib64/python3.10/site-packages/samba/netcmd/domain.py", line 555, in run
result = provision(self.logger,
File "/usr/lib64/python3.10/site-packages/samba/provision/__init__.py", line 2388, in provision
raise e
File "/usr/lib64/python3.10/site-packages/samba/provision/__init__.py", line 2378, in provision
forest = ForestUpdate(samdb, fix=True)
File …
```

Add python3-markdown dependency for python3-samba-dc

---

Makefile
ansible/del.vm.centos8.yml
ansible/del.vm.centos9.yml
ansible/prep.vm.centos8.yml
ansible/prep.vm.centos9.yml
ansible/test.rpms.centos8.yml
ansible/test.rpms.centos9.yml
vagrant/Vagrantfile

Given the fact that latest versions of vagrant libvirt boxes for CentOS Stream not getting referenced frequently we now switch to generic boxes.

Use generic CentOS boxes for testing built RPMs

---

ansible/roles/test.rpms.centos/tasks/main.yml
ansible/roles/test.rpms.fedora/tasks/main.yml
packaging/samba-master.spec.j2

* Build and test `samba-dc` package on CentOS Stream9
* Test installation of `samba-dc` on Fedora
fixes #5

Build and test DC packages

---

packaging/samba-4.17.spec.j2
packaging/samba-4.18.spec.j2

Installation test for `samba-dc` package failed on 4.17 and 4.18 release branches as I missed to make changes to corresponding spec files via https://github.com/samba-in-kubernetes/samba-build/commit/70511f0c1ade472b51275442caf1500e97e4d6d9. Therefore make necessary and similar changes to 4.17 and 4.18 spec files.

Enable AD DC packages on 4.17 and 4.18 release branches for CentOS Stream 9

---

Makefile
README.md
ansible/roles/prep.dirs/tasks/repo.yml
packaging/samba-4.17.spec.j2
packaging/samba-4.18.spec.j2
packaging/samba-master.spec.j2

* SPEC file cleanup
- [bz #2043178](https://bugzilla.redhat.com/show_bug.cgi?id=2043178) is now fixed.
- _.package_notes_file_ generation works with `ld.gold` on CentOS Stream 9 too.
- conditionally use `ld.mold` on Fedora 37 and higher.
* Default fedora version to build changed to 38.
* Update README to reflect recent changes.
* Remove `jq` installation task.
depends on #12  #9 https://github.com/samba-in-kubernetes/samba-centosci/pull/16

Few cleanups

---

packaging/samba-master.spec.j2

libauthn_policy is no longer a separate library but just a subsystem for building other libraries.
See [upstream change](https://git.samba.org/?p=samba.git;a=commit;h=b3a85655825fb6c6a1d668379c1ab004707dc56d) for details.

Do not include `libauthn_policy` as separate library

---

ansible/roles/prep.dirs/files/glusterfs-nightly-repo.tpl

Changes from https://github.com/gluster/centosci/commit/c23a78c4f43a1febd13d043e8e4408789bb5b6e9 modified the url where nightly built gluster packages were uploaded.

Fix base url for nightly gluster packages

---

ansible/roles/test.rpms.fedora/files/rpm-install.sh
packaging/samba-master.spec.j2

* Upstream recently [increased](https://git.samba.org/?p=samba.git;a=commit;h=b896da351c8b27440dfb895e866d5a5ce0320b21) minimum krb5 version required to build with AD DC components to 1.21.
- Considering the timing of this change it means that we need krb5 >= v1.21 for building Samba from v4.20.
* Unlike CentOS Stream 9 we don't expect updated(rebased) krb5 packages on Fedora 37 and lower.
* Adjust rpm-install script accordingly to check for OS version.

Bump minimum krb5 version requirement to 1.21

---

packaging/samba-master.spec.j2

Upstream recently [added](https://git.samba.org/?p=samba.git;a=commit;h=8107aafb40c22cacf56b69129e7c8611fd35184a) new IDL for smb3posix.

Add new smb3posix header file

---

packaging/samba-4.17.spec.j2
packaging/samba-4.18.spec.j2
packaging/samba-4.19.spec.j2
packaging/samba-master.spec.j2

`rpcecho` server is no longer enabled by default as its useful prominently in development and testing. This applies to builds with and without AD DC components.
See [3cf1beed](https://git.samba.org/?p=samba.git;a=commit;h=3cf1beed5df7d8b5d854517de7de322c6a5bc7fa) and [a9c32f92](https://git.samba.org/?p=samba.git;a=commit;h=a9c32f929b7901b4ca230cc7a725b42c8916540d) from upstream.

Include rpcecho server only with selftest

---

packaging/samba-master.spec.j2

See upstream change [422680f82f](https://git.samba.org/?p=samba.git;a=commit;h=422680f82fd0284cb747ea93fc9422c6bd721f68).

Add new user/auth submodule under netcmd

---

packaging/samba-master.spec.j2

See upstream change [21a3f60c](https://git.samba.org/?p=samba.git;a=commit;h=21a3f60cfc783d07994b29696c7a75e2372dd114).

Add new sub directory holding ndr tests

---

packaging/samba-master.spec.j2

Suffix used for private libraries built as part of Samba build process has found a new name 'private-samba' instead of 'samba4'. Refer [upstream change](https://git.samba.org/?p=samba.git;a=commit;h=f22df59b0655f9bb812c39734782b0ff3c71c954) for more details.

Rename private library names with new suffix

---

packaging/samba-4.18.spec.j2
packaging/samba-4.19.spec.j2
packaging/samba-master.spec.j2

`%autosetup` macro allows taking care of various individual steps needed alongside old `%setup` macro. The most prominent one being the process of applying patches which can be done with just an additional option to `%autosetup` taking away the extra `%patch` step. See [docs](https://rpm-software-management.github.io/rpm/manual/autosetup.html) for more details.

Use `%autosetup` instead of `%setup`

---

packaging/samba-master.spec.j2

* LDB is no longer built independently: see [!3524](https://gitlab.com/samba-team/samba/-/merge_requests/3524)
* New sub-commands to `samba-tool`
* Handling KDS: see [!3537](https://gitlab.com/samba-team/samba/-/merge_requests/3537)
* For service accounts: see [!3523](https://gitlab.com/samba-team/samba/-/merge_requests/3523)

New `samba-tool` sub-commands and no more independent LDB

---

packaging/samba-master.spec.j2

see upstream change [2de2d5dd20](https://git.samba.org/?p=samba.git;a=commit;h=2de2d5dd2018708eeca7e8a7c66015f81bcaf693).

Remove NFS event script and related unit tests

---

packaging/samba-master.spec.j2

Upstream references:
* [1f511acc13](https://git.samba.org/?p=samba.git;a=commit;h=1f511acc1338412cfd8f513b08c5c21a6d839e0a)
* [f739ef813c](https://git.samba.org/?p=samba.git;a=commit;h=f739ef813c037ebf201dae0af68d5e9276848145)

Move models out of netcmd python package to domain

---

packaging/samba-master.spec.j2

Upstream turned following python sources into independent modules:
* _policy.py_ in [c0e748f011](https://git.samba.org/?p=samba.git;a=commit;h=c0e748f0117308d36323001e1cf4387ca6c18297)
* _silo.py_ in [4d2c8ea957](https://git.samba.org/?p=samba.git;a=commit;h=4d2c8ea95783cafcbf954f7bfb040225cb693a68)

Add new python modules from policy.py and silo.py

---

packaging/samba-4.20.spec.j2

upstream [backport](https://git.samba.org/?p=samba.git;a=commit;h=9155d89a2ae04f45d809c46129687c6f5a510a0d) to v4.20 release branch
Moved from samba-client to base package.

Rearrange and package samba-bgqd service components

---

packaging/samba-master.spec.j2

Upstream recently [removed](https://git.samba.org/?p=samba.git;a=commit;h=991d21d075c0382b27dc9da64e8a6cfd94f175c0) a old hack related to CTDB sudoers config.

Remove CTDB sudoers related config and unit test

---

packaging/samba-master.spec.j2

See upstream change [415f9f0745](https://git.samba.org/?p=samba.git;a=commit;h=415f9f07456e3fd24063e7508d8b2553df020c21).

Include statd_callout and statd_callout_helper

---

packaging/samba-master.spec.j2

Unlike _vfs_ceph_, _vfs_ceph_snapshots_ is an independent module that can be stacked atop ceph kclient. So move it to the base package containing other vfs modules instead of shipping it inside `samba-vfs-cephfs`.
_Originally posted by @Shwetha-Acharya in https://github.com/samba-in-kubernetes/sit-environment/pull/105#discussion_r1656846777_

Include ceph_snapshots VFS module within base package

---

packaging/samba-master.spec.j2

* `trusts_util` lib merged into `ads` via [3de8d294](https://git.samba.org/?p=samba.git;a=commit;h=3de8d2941529af5a89069bd8e0caed0bcb508869)
* Add new _46.update-keytabs.script_ from [1fcaf066](https://git.samba.org/?p=samba.git;a=commit;h=1fcaf066f42cf01c6978416e99b132fdbb1f55de)
* Package `vfs_ceph_new` [!3718](https://gitlab.com/samba-team/samba/-/merge_requests/3718)

Few RPM spec file updates

---

Makefile
README.md
ansible/build.rpms.rhel.yml
ansible/roles/build.rpms.rhel/files/rpm-build.sh
ansible/roles/build.rpms.rhel/tasks/main.yml
ansible/roles/prep.dirs/files/epel-restricted.tpl
ansible/roles/prep.dirs/tasks/main.yml
ansible/roles/prep.dirs/tasks/repo.yml
ansible/roles/test.rpms.rhel/files/rpm-install.sh
ansible/roles/test.rpms.rhel/tasks/main.yml
ansible/test.rpms.rhel.yml
packaging/samba-master.spec.j2

Few considerations from the approach used here:
- In order to satisfy the dependency for _libthrift_ from ceph we restrictively enable EPEL during build and installation testing process.
- Unless you build rhel rpms on a registered system, following environment variables are expected to be present in the execution environment for registration purposes in a podman container:
- `ORG_ID` : ID to register with one of multiple organizations
- `ACT_KEY`: activation key name to use for registration
> NOTE: In the absence of any of these variables it is assumed that the build is attempted on a registered system resulting in rpms being built locally using mock.
fixes #47 
depends on #50

Add support for RHEL builds

---

packaging/samba-master.spec.j2

* Exclude `vfs_ceph` man page for builds without _libcephfs_ support.
* Even though `vfs_ceph_snapshots` doesn't require _libcephfs_, it is only built when `vfs_ceph` is enabled. Accordingly exclude the corresponding man page if the module itself is not present.

rpmspec: Conditionally exclude ceph manual pages

---

packaging/samba-master.spec.j2

For not so long _ldb_version.h_ was incorrectly installed even when it was built as private. This was fixed recently in [upstream](https://git.samba.org/?p=samba.git;a=commit;h=5851ae555425ea2ba8e431162142ebae47be802e) to only install when explicitly not mentioned in the list of bundled libraries.

rpmspec: Fix mispackaging of ldb_version.h

---

packaging/samba-4.20.spec.j2

* New ceph vfs module is now available with v4-20-test. See [bug #15686](https://bugzilla.samba.org/show_bug.cgi?id=15686) for more details.
* Backport following ceph related changes from master spec file:
- 77450fe9bfb4cf8a578e75e1ebd09f1d28c305e0
- 37e864654244c092be3b9ac625db7cfbf84abd80

rpmspec: Backport ceph related changes to 4.20

---

packaging/samba-master.spec.j2

* CTDB's native smnotify got removed in favour of similar one from nfs-util. [!3721](https://gitlab.com/samba-team/samba/-/merge_requests/3721)
* Support for persistent TDB backups. [!3764](https://gitlab.com/samba-team/samba/-/merge_requests/3764)

rpmspec: Sync recent CTDB changes

---

Makefile
ansible/roles/prep.dirs/files/ceph-repo.tpl.j2

- `ceph_repo_gpgkey` in its absence is an undefined variable. Therefore explicitly check whether it is defined or not.
- Fix misplacement of hyphen(`-`) in Makefile.

prep.dirs: Fix `if` condition in ceph repo template

---

packaging/samba-4.21.spec.j2
packaging/samba-master.spec.j2

_mdb_ backend for _ldb_ is now [built](https://gitlab.com/samba-team/samba/-/merge_requests/3807) irrespective of whether AD DC components are enabled or not. Therefore remove the conditional for including _mdb.so_ library.
Since our RPM jobs always build with AD DC this went unnoticed until RHEL builds were attempted where AD DC bits are excluded.
The underlying change is now available with 4.21 release series.

rpmspec: Include always built mdb.so

---

README.md
ansible/build.rpms.fedora.yml
ansible/test.rpms.fedora.yml

depends on https://github.com/samba-in-kubernetes/samba-centosci/pull/72

Update README and make v41 the default for Fedora

---

packaging/samba-4.21.spec.j2

upstream [backport](https://git.samba.org/?p=samba.git;a=commit;h=0dccda38f27b3bbda5d2a4de588a333ff554651a) to v4-21-stable branch.
Previously #68 added it to the master spec file.

Add new crypt wrapper library(backport to 4.21)

---

packaging/samba-master.spec.j2

Previously the man page for smb prometheus endpoint was always built irrespective of the configure option `--with-prometheus-exporter`. This is now fixed in upstream to only build/install when required configure option is specified.
ref: [4c946acb](https://git.samba.org/?p=samba.git;a=commit;h=4c946acb40d616cacbee02bbdb195b629f7f5cd3)

rpmspec: Remove the exclude for prometheus endpoint man page

---

packaging/samba-master.spec.j2

These are created based on sources from the following repositories:
- https://github.com/lxin/quic
- https://github.com/ngtcp2/ngtcp2
Since the kernel implementation is still not merged there's also a wrapper which is only built when configured with `--enable-selftest`. For now it is ignored as the wrapper may finally end up in its own repository than Samba in the near future.
ref: [!4019](https://gitlab.com/samba-team/samba/-/merge_requests/4019)

Add new third_party libraries for SMB over QUIC

---

ansible/roles/prep.dirs/files/glusterfs-nightly-repo.tpl
ansible/roles/prep.dirs/files/sig-storage-gluster.tpl
ansible/roles/prep.dirs/tasks/main.yml
ansible/roles/prep.dirs/tasks/repo.yml
ansible/roles/test.rpms.centos/files/rpm-install.sh
packaging/samba-4.21.spec.j2
packaging/samba-4.22.spec.j2
packaging/samba-master.spec.j2

- Switch to Storage SIG repo for GlusterFS because nightly glusterfs repo doesn't have aarch64 packages.
- Rearrange and enable building samba-vfs-glusterfs on aarch64.

rpmspec: Build samba-vfs-glusterfs on aarch64
